PlanktoScope/device-backend

- control/pscopehat/main.py
This PR updates the pscopehat version of the controller to save its log files to the same location as the adafruithat version of the controller.
> Fix the path for pscopehat controller log files

- CHANGELOG.md
- default-configs/adafruithat-latest.hardware.json
- default-configs/v2.1.hardware.json
The default `hardware.json` file for PlanktoScope v2.1 had incorrect keys for the white balance values - the names were `wb_red_gain` and `wb_blue_gain`, when they should've been `red_gain` and `blue_gain`. This PR changes those keys to their correct names.
> Fix white balance keys in the default hardware config for v2.1

- CHANGELOG.md
This PR updates `CHANGELOG.md` so that we can add a prerelease tag at v2023.9.0-beta.0.
> Bump version numbers for v2023.9.0-beta.0

- CHANGELOG.md
- control/adafruithat/main.py
- control/adafruithat/planktoscope/display.py
- control/adafruithat/planktoscope/identity.py
- control/adafruithat/planktoscope/imager/__init__.py
- control/pscopehat/main.py
- control/pscopehat/planktoscope/display.py
- control/pscopehat/planktoscope/identity.py
- control/pscopehat/planktoscope/imager/__init__.py
- processing/segmenter/planktoscope/identity.py
- processing/segmenter/planktoscope/segmenter/__init__.py
- processing/segmenter/planktoscope/uuidName.py
This PR is related to https://github.com/PlanktoScope/PlanktoScope/issues/207 and https://github.com/PlanktoScope/PlanktoScope/issues/203. It restores the `uuidName` module (which generates machine names from RPi serial numbers in the old "Baba"-based naming scheme) to the data processing segmenter, since the segmenter logs that name. It also logs the machine names in the new naming scheme; machine names are just loaded from a file on the filesystem (currently hard-coded as `/home/pi/.local/etc/machine-name`; but will be overridable with an environment variable in the future), rather than being computed in Python. This enables a better separation of concerns, since determination of the machine name is more of an OS-level concern; for example, if we run the segmenter in a Docker container …
> Use the new machine naming scheme

- default-configs/adafruithat-latest.hardware.json
- default-configs/pscopehat-latest.hardware.json
- default-configs/v2.1.hardware.json
- default-configs/v2.3.hardware.json
- default-configs/v2.5.hardware.json
This PR fixes part of https://github.com/PlanktoScope/PlanktoScope/issues/210 by including a pixel size calibration of 0.75 um/pixel as the default value for all default hardware configurations.
> Add pixel size calibration to all default configs

- CHANGELOG.md
- control/pyproject.toml
- processing/segmenter/pyproject.toml
This PR bumps the version to v2023.9.0-beta.1 in preparation for the next beta prerelease of the software distro.
> Bump version numbers for v2023.9.0-beta.1

- CHANGELOG.md
- control/adafruithat/planktoscope/identity.py
- control/pscopehat/planktoscope/identity.py
- processing/segmenter/planktoscope/identity.py
This PR updates the backend to load the machine name from `/var/lib/planktoscope/machine-name`, due to the changes made in https://github.com/PlanktoScope/PlanktoScope/pull/350 and https://github.com/PlanktoScope/device-pkgs/pull/5 and https://github.com/PlanktoScope/pallet-standard/pull/5.
> Change the path of the machine-name file to load

- default-configs/v2.5.hardware.json
- default-configs/v2.6.hardware.json
This PR fixes errors in the v2.5 and v2.6 hardware config files, where the pixel size calibration values for those two versions had previously been incorrectly swapped.
> Fix incorrect pixel calibration sizes for v2.5 & v2.6 hardware

- .github/workflows/processing-segmenter-build.yml
- CHANGELOG.md
- control/pyproject.toml
- processing/segmenter/Dockerfile
- processing/segmenter/pyproject.toml
This PR reverts a change introduced in #17, which had dropped the user from `root` to `pi` for [security reasons](https://pythonspeed.com/articles/root-capabilities-docker-security/). However, that caused problems because bind mounts of nonexistent directories on the host are created by the Docker daemon (which we're running with root privileges) with root ownership, so that the segmenter container itself is unable to access such directories; and because subdirectories of `/home/pi/data/img` are created on the host by the Python hardware controller with root ownership, so that the segmenter container is unable to create `done.txt` files under those subdirectories (as reported by @tpollina in https://planktoscope.slack.com/archives/C015K99AJAE/p1708530438903539).
A longer-term solution …
> Stop dropping root in segmenter container

- .github/workflows/processing-segmenter-build.yml
This PR follows up on a change in #22 to try to resolve a failure of the "merge" job (for merging Docker container images for different architectures into a single multi-arch image entry) when GitHub Actions runs the job in the merge queue.
> Try again to fix GH Actions errors in merge group

- .github/workflows/processing-segmenter-build.yml
The segmenter CI docker-build-and-push action has been failing in #28 and #29 because it's trying to push container images up to https://github.com/orgs/PlanktoScope/packages from branches in forked repositories. This is not possible because `GITHUB_TOKEN` is [read-only for such PRs](https://docs.github.com/en/actions/security-guides/automatic-token-authentication#permissions-for-the-github_token). This PR attempts to disable push-related functionality from such PRs.
> Don't push container images in PRs from forks

- control/adafruithat/planktoscope/camera/hardware.py
- control/adafruithat/planktoscope/camera/mqtt.py
- control/adafruithat/planktoscope/imagernew/mqtt.py
- control/adafruithat/planktoscope/imagernew/stopflow.py
- control/planktoscopehat/planktoscope/camera/hardware.py
- control/planktoscopehat/planktoscope/camera/mqtt.py
- control/planktoscopehat/planktoscope/imagernew/mqtt.py
- control/planktoscopehat/planktoscope/imagernew/stopflow.py
This PR follows up on #19 by:
- Fixing some errors (e.g. things which were out-of-date) and making other improvements to the docstrings and code comments for the classes/methods/functions in the `camera` and `imagernew` subpackages
- Simplifying the `camera.mqtt.Worker` class's external interface for accessing its camera hardware wrapper, by removing a `threading.Event` object which previously had to be checked by external code and instead performing that check as part of a new property accessor for the camera hardware wrapper.
> Iterate on code comments and internal APIs for `camera` and `imagernew`

- CHANGELOG.md
- processing/segmenter/planktoscope/segmenter/__init__.py
- processing/segmenter/planktoscope/segmenter/operations.py
This PR implements a requirement which @tpollina added to the v2024.0.0 milestone as a **breaking change** to make for the v2024.0.0-beta.0 prerelease (refer to the [2024-04-11 software meeting](https://docs.google.com/document/d/1Iba0_9yNFEDdp1Qy8IYlLP43Ga0DnDr3CdavWV0QGZY/edit#heading=h.e3f0mm3ng2sj) for context) to the behavior of the segmenter, so that by default it will no longer subtract consecutive masks from each other in the frame-processing pipeline.
Following a suggestion by @W7CH , I have made it possible for users to re-enable the behavior which this PR changes to be disabled by default - specifically, the segmenter now checks to see if the environment variable `SEGMENTER_PIPELINE_SUBTRACT_CONSECUTIVE_MASKS` is set to `true`, and if so, then the segmenter will perform …
> Only subtract consecutive masks when an env var is set

- CHANGELOG.md
- control/README.md
- control/adafruithat/planktoscope/camera/hardware.py
- control/adafruithat/planktoscope/camera/mqtt.py
- control/planktoscopehat/planktoscope/camera/hardware.py
- control/planktoscopehat/planktoscope/camera/mqtt.py
- control/pyproject.toml
This PR fixes various issues identified in the [2024-04-11 software meeting](https://docs.google.com/document/d/1Iba0_9yNFEDdp1Qy8IYlLP43Ga0DnDr3CdavWV0QGZY/edit#heading=h.e3f0mm3ng2sj) as blockers for the v2024.0.0-beta.0 software prerelease, namely:
- The conversion factors between ISO and image gain were using incorrect scaling factors.
- The image quality of the camera preview stream was not adequate for image focusing.
This PR also includes a basic (minimum viable) implementation of a poethepoet command (using SCP) to help make it easy to upload the local copy of hardware controller Python files to a PlanktoScope over ssh, following an idea raised during a discussion with @Oumayma-hy in the [2024-04-18 software meeting](https://docs.google.com/document/d/1Iba0_9yNFEDdp1Qy8IYlLP43Ga0Dn …
> Fix various picamera2 camera settings

- CHANGELOG.md
- default-configs/fairscope-latest.hardware.json
This PR (along with https://github.com/PlanktoScope/PlanktoScope/pull/430) is part of a prototype for a discussion in the [2024-06-13 software meeting](https://docs.google.com/document/d/1yqRMceF52-kezI2drtvw3Zbv9zkgCo27n7X2q2vmAeI/edit#heading=h.8qcosaymfqo0) about pulling back the default hardware version for the `planktoscopehat` build of the PlanktoScope OS from v2.6 back to v2.5 (reverting a change made in #12 and 118ea1e13212826319fa3b818987124fe2d4dfae) and instead using v2.6 as the default hardware version for a FairScope-specific build of the Planktoscope OS.
> Pull back default planktoscopehat hardware config to v2.5 hardware

- .github/workflows/release-channel-beta.yml
- CHANGELOG.md
- control/adafruithat/planktoscope/camera/hardware.py
- control/adafruithat/planktoscope/camera/mqtt.py
- control/planktoscopehat/planktoscope/camera/hardware.py
- control/planktoscopehat/planktoscope/camera/mqtt.py
This PR is part of a fix for a regression reported to me (privately, in DMs) by @fabienlombard on PlanktoScope OS v2024.0.0-beta.1, in which the default ISO setting displayed on the Node-RED dashboard was inconsistent with the actual initial image gain (of 1.0, which corresponds to an ISO of ~54 on the PlanktoScope hardware v2.1's camera and an ISO of ~43 on the PlanktoScope hardware v2.3+'s camera). This PR initializes the image gain value to match a consistent ISO setting of 150, which will become the default ISO setting for both the adafruithat Node-RED dashboard and the planktoscopehat Node-RED dashboard.
This fix was discussed and approved in the [2024-07-25 software meeting](https://docs.google.com/document/d/1yqRMceF52-kezI2drtvw3Zbv9zkgCo27n7X2q2vmAeI/edit#heading=h.6csyvp7b4rjc).
> Initialize camera image gain to a consistent ISO of 150

- CHANGELOG.md
- control/adafruithat/planktoscope/camera/hardware.py
- control/adafruithat/planktoscope/camera/mjpeg.py
- control/adafruithat/planktoscope/camera/mqtt.py
- control/planktoscopehat/planktoscope/camera/hardware.py
- control/planktoscopehat/planktoscope/camera/mjpeg.py
- control/planktoscopehat/planktoscope/camera/mqtt.py
- processing/segmenter/Dockerfile
This PR implements the workaround proposed at https://planktoscope.slack.com/archives/C01V5ENKG0M/p1732209129043269 to reduce the occurrence/severity of camera preview latency events discussed/troubleshooted at https://planktoscope.slack.com/archives/C01V5ENKG0M/p1724939562549999 and the [2024-10 - 2024-11 software meetings](https://docs.google.com/document/d/1Sq0rqxOLi0h2hlvAo50e_UXm2fOa1FaKFnn4CNLB8TI/edit?tab=t.0). Specifically, this PR adjusts camera preview stream parameters and adds a stream framerate limiter.
TODOs:
> Try to mitigate camera preview stream latency problems

- CHANGELOG.md
- processing/segmenter/Dockerfile
- processing/segmenter/planktoscope/segmenter/__init__.py
This PR is part of a fix for https://github.com/PlanktoScope/PlanktoScope/issues/114 ; this PR makes the fix which was proposed at https://github.com/PlanktoScope/PlanktoScope/issues/89#issuecomment-2405625882 , discussed in the [2024-10-17 software meeting](https://docs.google.com/document/d/1Sq0rqxOLi0h2hlvAo50e_UXm2fOa1FaKFnn4CNLB8TI/edit?tab=t.0#heading=h.e1cyde8yk5va), and approved (by Thibaut) in the [2024-10-24 software meeting](https://docs.google.com/document/d/1Sq0rqxOLi0h2hlvAo50e_UXm2fOa1FaKFnn4CNLB8TI/edit?tab=t.0#heading=h.porgcudwb01c) for inclusion in v2024.0.0 of PlanktoScope OS.
TODO:
> Fix incorrect segmenter object size thresholding calculations

- .github/workflows/control-build.yml
- .github/workflows/merge-gatekeeper.yml
- .github/workflows/processing-segmenter-build.yml
- processing/segmenter/README.md
This PR attempts to avoid needing to run CI checks for the hardware controller on PRs which only modify the segmenter (and vice versa), by adding https://github.com/upsidr/merge-gatekeeper and making that the only required check.
> Use merge gatekeeper to avoid running slow CI workflows when not needed

- CHANGELOG.md
- processing/segmenter/planktoscope/segmenter/ecotaxa.py
This PR fixes a problem reported by @fabienlombard [on the PlanktoScope Slack workspace](https://planktoscope.slack.com/archives/C01V5ENKG0M/p1733327391060119), in which the segmenter's behavior to set the `img_rank` metadata field to the index of the image in the entire dataset was incorrect; that rank is instead supposed to be used to set a display priority among alternate images (e.g. brightfield vs fluorescence) corresponding to the same object. And EcoTaxa cannot handle `img_rank` values above ~32700, so larger datasets exported by the segmenter could not be imported to EcoTaxa. Now we just set `img_rank` to `1` for all object images, since we only export one image per object.
> Fix incorrect use of `img_rank` field in EcoTaxa export metadata

- processing/segmenter/planktoscope/segmenter/__init__.py
This PR responds to a request @fabienlombard sent to me in a group DM:
> do you have a way to have temporarily a way to have the log to tells (when doing the flat calculation) what lists of image the segmenter is actually using to generate the “flat”
This PR adjusts a debug logging message in the "flat calculation" step to report the number (and filenames) of images being used in that step.
> Make segmenter "flat calculation" debug logs more detailed

- .github/workflows/control-build.yml
- .github/workflows/processing-segmenter-build.yml
- CHANGELOG.md
- control/adafruithat/planktoscope/imager/mqtt.py
- control/planktoscopehat/planktoscope/imager/mqtt.py
- control/poetry.lock
- control/pyproject.toml
- processing/segmenter/Dockerfile
- processing/segmenter/poetry.lock
- processing/segmenter/pyproject.toml
This PR is part of https://github.com/PlanktoScope/PlanktoScope/pull/538 to make the `/home/pi/data` directory - including its subdirectories - have ownership by the `pi` user.
This PR also fixes a bug discovered during testing, in which reuse of an already-used acquisition ID did not correctly terminate data acquisition (likely a regression introduced by #19)
> Make segmenter run as user `pi`

- CHANGELOG.md
- control/adafruithat/planktoscope/imagernew/mqtt.py
- control/planktoscopehat/planktoscope/imagernew/mqtt.py
- control/pyproject.toml
This PR fixes a regression introduced in PR #48 in which the value of the ISO metadata field (such as in the metadata exported to EcoTaxa) no longer corresponded with the user-set ISO setting, but instead was a constant scaling of the image gain (which PR #48 changed to be calculated from the ISO setting based on a scaling factor specific to the camera model, instead of a constant scaling of the ISO setting).
This PR also bumps the version number for a v2024.0.1-beta.0 hotfix beta prerelease.
> Use camera-specific ISO calibration for ISO values in dataset metadata
